tulip: Use shell-script $$(...) instead of $(shell ...)
kati doesn't support passing results of $(shell)
to other make constructs, as explained here:
https://github.com/google/kati/issues/71

Fixes the following building error:

error: kati doesn't support passing results of $(shell) to other make constructs: date -u +%s

Signed-off-by: GhostMaster69-dev <rathore6375@gmail.com>